name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout branch
      uses: actions/checkout@v1
    - name: Debug
      run:
        echo TEMP_CHANGELOG.md
    - name: Install github-release-notes and generate changelog
      run: |
        npm install
        ./node_modules/.bin/gren release --token=${{ secrets.GITHUB_TOKEN }}
      env:
        CI: true
    # - name: Create and publish realese
    #   uses: ncipollo/release-action@v1
    #   with:
    #     bodyFile: 'TEMP_CHANGELOG.md'
    #     token: ${{ secrets.GITHUB_TOKEN }}
    # - name: Debug
    #   run:
    #     echo TEMP_CHANGELOG.md

