name: Release

on:
  push:
    # branches to consider in the event; optional, defaults to all
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: install github-release-notes and generate changelog
      run: |
        npm install github-release-notes
        ./node_modules/.bin/gren changelog --generate --override --token=${{ secrets.GITHUB_TOKEN }}
      env:
        CI: true
    - uses: ncipollo/release-action@v1
      with:
        bodyFile: 'CHANGELOG.md'
        token: ${{ secrets.GITHUB_TOKEN }}

