name: Release

on:
  push:
    # branches to consider in the event; optional, defaults to all
    # tags:
    #   - 'v*'
    branched:
      master

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Create Release Notes
        uses: docker://decathlon/release-notes-generator-action:2.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OUTPUT_FOLDER: temp_release_notes
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: release_file.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}