name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout branch
      uses: actions/checkout@v1
    - name: Debug
      run:
        echo TEMP_CHANGELOG.md
    - name: Install github-release-notes and generate changelog
      run: |
        echo $(node -p -e "require('./package.json').version")
        npx github-release-notes release --tags=v$(node -p -e "require('./package.json').version") --token=${{ secrets.GITHUB_TOKEN }} -B
    # - name: Create and publish realese
    #   uses: ncipollo/release-action@v1
    #   with:
    #     bodyFile: 'TEMP_CHANGELOG.md'
    #     token: ${{ secrets.GITHUB_TOKEN }}
    # - name: Debug
    #   run:
    #     echo TEMP_CHANGELOG.md

