name: Release

on:
  push:
    # branches to consider in the event; optional, defaults to all
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ncipollo/release-action@v1
      with:
        draft: true
        body: |
          ### Тестовый тестович
        token: ${{ secrets.GITHUB_TOKEN }}
    - uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

